
#ifndef __EN_PHONOLOGY__
#define __EN_PHONOLOGY__


#include "phonetics.h"

enum EnglishPhonemes {

	SHORTVOWEL_I = 1,
	SHORTVOWEL_U,
	SHORTVOWEL_MID_CENTRAL_E,
	SHORTVOWEL_OPENMID_FRONT_E,
	SHORTVOWEL_OPEN_FRONT_A,
	SHORTVOWEL_OPEN_CENTRAL_A,
	SHORTVOWEL_OPENMID_BACK_O,
	SHORTVOWEL_MID_FRONT_E,
	SHORTVOWEL_CLOSEMID_BACK_O,
	SCHWA,
	LONGVOWEL_I,
	LONGVOWEL_U,
	LONGVOWEL_E,
	LONGVOWEL_O,
	LONGVOWEL_A,
	CONSONANT_P,
	CONSONANT_B,
	CONSONANT_T,
	CONSONANT_D,
	CONSONANT_K,
	CONSONANT_G,
	CONSONANT_M,
	CONSONANT_N,
	CONSONANT_NG,
	CONSONANT_F,
	CONSONANT_V,
	CONSONANT_TH0,
	CONSONANT_TH1,
	CONSONANT_S,
	CONSONANT_Z,
	CONSONANT_SH,
	CONSONANT_ZH,
	CONSONANT_H,
	CONSONANT_CH,
	CONSONANT_DJ,
	CONSONANT_R,
	CONSONANT_J,
	CONSONANT_W,
	CONSONANT_L
};

#endif
