
#ifndef __TACTICS__
#define __TACTICS__

#include <vector>
#include <iterator>

enum PhonemeNames {
	kNULL_SET,

	// onsets
	kCONSONANT_BUT_MU,
	kPLOSIVE_PLUS_APPROXIMANT_BUT_J,
	kVOICELESS_FRICATIVE_PLUS_APPROXIMANT_BUT_J,
	kCONSONANT_PLUS_J,
	kS_PLUS_VOICELESS_PLOSIVE,
	kS_PLUS_NASAL,
	kS_PLUS_VOICELESS_FRICATIVE,
	kS_PLUS_VOICELESS_PLOSIVE_PLUS_APPROXIMANT,

	// codas

	kCONSONANT_BUT_H_W_J,
	kLATERAL_APPROXIMANT_PLUS_PLOSIVE,
	kLATERAL_APPROXIMANT_PLUS_FRICATIVE,
	kLATERAL_APPROXIMANT_PLUS_AFFRICATE,
	kLATERAL_APPROXIMANT_PLUS_NASAL,
	kNASAL_PLUS_HOMORGANIC_PLOSIVE,
	kNASAL_PLUS_FRICATIVE,
	kNASAL_PLUS_AFFRICATE,
	kVOICELESS_FRICATIVE_PLUS_VOICELESS_PLOSIVE,
	kVOICELESS_FRICATIVE_PLUS_VOICELESS_FRICATIVE,
	kVOICELESS_PLOSIVE_PLUS_VOICELESS_PLOSIVE,
	kPLOSIVE_PLUS_VOICELESS_FRICATIVE,
	kLATERAL_APPROXIMANT_PLUS_CONSONANT_PLUS_CONSONANT,
	kNASAL_PLUS_HOMORGANIC_PLOSIVE_PLUS_PLOSIVE,
	kNASAL_PLUS_HOMORGANIC_PLOSIVE_PLUS_FRICATIVE,
	kTHREE_OBSTRUENT,

	// nuclei

	kLONG_VOWEL,
	kSHORT_VOWEL,
	kDIPHTHONG,
	kTRIPHTHONG,
	kSYLLABIC_CONSONANT
};

#define NUM_ONSETS	8
#define NUM_CODAS	16
#define NUM_NUCLEI	5

struct PhonemeSet {

	int			_name;
	int			_size;
	const char **_phonemes;

	PhonemeSet(int name, int size, const char *phonemes[]) : _name(name), _size(size), _phonemes(phonemes) {
	}

	int size() const {
		return _size;
	}

	const char*	operator[](int index) const {
		return _phonemes[index];
	}

};


#endif
